name: driver_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  auto_size_text: ^3.0.0
  cached_network_image: ^3.4.1
  camera: ^0.11.1
  chewie: ^1.8.1
  connectivity_plus: ^6.0.5
  cupertino_icons: ^1.0.8
  dio: ^5.7.0
  dotted_border: ^2.1.0
  dropdown_button2: ^2.3.9
  file_picker: ^8.1.2
  firebase_core: ^3.10.1
  firebase_messaging: ^15.2.1
  fl_chart: ^0.69.0
  flutter_local_notifications: ^18.0.1
  flutter_polyline_points: ^2.1.0
  flutter_rating_bar: ^4.0.1
  flutter_screenutil: ^5.9.3
  flutter_slidable: ^3.1.1
  flutter_svg: ^2.0.10+1
  fluttertoast: ^8.2.8
  flutter_widget_from_html_core: ^0.15.2
  get: ^4.6.6
  get_it: ^8.0.2
  get_storage: ^2.1.1
  google_fonts: ^6.2.1
  google_maps_flutter: ^2.10.0
  image_picker: ^1.1.2
  intl: ^0.19.0
  jwt_decoder: ^2.0.1
  location: ^8.0.0
  local_auth: ^2.3.0
  lottie: ^3.1.2
  package_info_plus: ^8.2.0
  path_provider: ^2.1.4
  permission_handler: ^11.3.1
  pinput: ^5.0.0
  pull_to_refresh: ^2.0.0
  signature: ^5.5.0
  smooth_page_indicator: ^1.2.0+3
  socket_io_client: ^3.0.0
  syncfusion_flutter_pdfviewer: ^27.1.52
  video_player: ^2.9.1
  widget_to_marker: ^1.0.6
  sentry_flutter: ^8.13.2


dev_dependencies:
  flutter_test:
    sdk: flutter
    
  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: 4.0.0
  flutter_launcher_icons: ^0.14.0

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  remove_alpha_ios: true
  # image_path: "assets/image/app_icon.png"
  image_path_android: "assets/image/app_icon.png" # Path to your default icon (used if theme detection fails)
  image_path_ios: "assets/image/app_icon.png" # Path to your default icon (used if theme detection fails)
  adaptive_icon_background: "#FFFFFF" # Background color for adaptive icons (light mode default)
  adaptive_icon_foreground: "assets/image/app_icon.png" # Light mode icon
  android_adaptive_icon_background: "#212121" # Background color for adaptive icons (dark mode default)
  android_adaptive_icon_foreground: "assets/image/app_icon.png" # Dark mode icon

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  generate: true #Used for localization

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/image/
    - assets/svg/
    - assets/lottie/
    - assets/video/
    - assets/gif/

flutter_assets:
  assets_path: assets/
  output_path: lib/core/constants/
  filename: app_assets.dart

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
