name: employee_app
description: "Employee App to maintain the task"
publish_to: 'none'
version: 3.3.18+3.3.18

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  auto_size_text: ^3.0.0
  cached_network_image: ^3.4.1
  camera: ^0.11.1
  connectivity_plus: ^6.1.4
  cupertino_icons: ^1.0.8
  dio: ^5.8.0+1
  dotted_border: ^3.0.1
  dropdown_button2: ^2.3.9
  easy_date_timeline: ^2.0.9
  file_picker: ^10.1.7
  firebase_core: ^3.15.1
  firebase_messaging: ^15.2.9
  firebase_crashlytics: ^4.3.10
  firebase_analytics: ^11.5.2
  fl_chart: ^1.0.0
  flutter_local_notifications: ^19.3.0
  # flutter_polyline_points: ^2.1.0
  flutter_screenutil: ^5.9.3
  flutter_secure_storage: ^9.2.4
  flutter_slidable: ^4.0.0
  flutter_svg: ^2.1.0
  fluttertoast: ^8.2.12
  get: ^4.7.2
  get_it: ^8.0.3
  google_fonts: ^6.2.1
  google_maps_flutter: ^2.12.1
  image_picker: ^1.1.2
  intl: ^0.20.2
  jwt_decoder: ^2.0.1
  local_auth: ^2.3.0
  location: ^8.0.0
  package_info_plus: ^8.3.0
  path_provider: ^2.1.5
  permission_handler: ^12.0.0+1
  pinput: ^5.0.1
  pull_to_refresh_new: ^2.0.5
  socket_io_client: ^3.1.2
  syncfusion_flutter_pdfviewer: ^30.1.38
  url_launcher: ^6.3.1
  widget_to_marker: ^1.0.6
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.6

flutter_native_splash:
  color: "#FFFFFF"
  image: "assets/image/app_icon.png"
  android: true
  ios: true
  fullscreen: true

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  remove_alpha_ios: true
  # image_path: "assets/image/app_icon.png"
  image_path_android: "assets/image/app_icon.png" # Path to your default icon (used if theme detection fails)
  image_path_ios: "assets/image/app_icon.png" # Path to your default icon (used if theme detection fails)
  adaptive_icon_background: "#FFFFFF" # Background color for adaptive icons (light mode default)
  adaptive_icon_foreground: "assets/image/app_icon.png" # Light mode icon
  android_adaptive_icon_background: "#212121" # Background color for adaptive icons (dark mode default)
  android_adaptive_icon_foreground: "assets/image/app_icon.png" # Dark mode icon

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  generate: true #Used for localization

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/image/
    - assets/svg/
    - assets/svg/car_parts/
    - assets/svg/left_section/
    - assets/svg/middle_section/
    - assets/svg/right_section/
    - assets/svg/general/
    - assets/gif/

flutter_assets:
  assets_path: assets/
  output_path: lib/core/constants/
  filename: app_assets.dart

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
