// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAH7ybPEFC0EDfuFNc8dfG_JnYcZkuHUGo',
    appId: '1:1015286480930:android:f272bb53df262bb5864a7b',
    messagingSenderId: '1015286480930',
    projectId: 'fb-mobile-app-a329f',
    storageBucket: 'fb-mobile-app-a329f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8IhBQRP3u6yor9eYVK9WUYJ0UmMrO27E',
    appId: '1:1015286480930:ios:b41e88b9511ea58f864a7b',
    messagingSenderId: '1015286480930',
    projectId: 'fb-mobile-app-a329f',
    storageBucket: 'fb-mobile-app-a329f.firebasestorage.app',
    iosBundleId: 'com.fleetblox.employeeApp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2NznoV_ccvv9LbcFBwCcN_sDYvoo8-Po',
    appId: '1:1015286480930:web:924d5b960ee3164c864a7b',
    messagingSenderId: '1015286480930',
    projectId: 'fb-mobile-app-a329f',
    authDomain: 'fb-mobile-app-a329f.firebaseapp.com',
    storageBucket: 'fb-mobile-app-a329f.firebasestorage.app',
    measurementId: 'G-3EHSB1Y0RL',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8IhBQRP3u6yor9eYVK9WUYJ0UmMrO27E',
    appId: '1:1015286480930:ios:b41e88b9511ea58f864a7b',
    messagingSenderId: '1015286480930',
    projectId: 'fb-mobile-app-a329f',
    storageBucket: 'fb-mobile-app-a329f.firebasestorage.app',
    iosBundleId: 'com.fleetblox.employeeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD2NznoV_ccvv9LbcFBwCcN_sDYvoo8-Po',
    appId: '1:1015286480930:web:6f2f528b81a60968864a7b',
    messagingSenderId: '1015286480930',
    projectId: 'fb-mobile-app-a329f',
    authDomain: 'fb-mobile-app-a329f.firebaseapp.com',
    storageBucket: 'fb-mobile-app-a329f.firebasestorage.app',
    measurementId: 'G-9G31LKFKWF',
  );

}