import 'dart:io';
import 'dart:async';
import 'dart:math' as math show sin, pi;

import 'package:dropdown_button2/dropdown_button2.dart';
import 'package:flutter/services.dart';
import 'package:flutter_svg/svg.dart';
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:get/get.dart';

import '../../core/l10n/app_localizations.dart';
import '../../core/constants/app_assets.dart';
import '../../core/router/router_paths.dart';
import '../../features/drawer/controller/drawer_controller.dart';
import '../../features/drawer/view/widgets/app_drawer.dart';
import '../../features/maintenance/view/widgets/widget_imports.dart';
import '../../features/more/model/country_code_model.dart';
import '../../features/notification/controller/notification_controller.dart';
import '../extensions/validator_extension.dart';
import '../../core/constants/app_color.dart';
import '../repository/local/debounce_repo.dart';
import '../services/remote/socket_service.dart';
import '../services/service_locator.dart';

import 'network_image_widget.dart';
import 'border_card_widget.dart';

part 'solid_text_button.dart';
part 'solid_button.dart';
part 'loading_widget.dart';
part 'no_data_found_widget.dart';
part 'image_placeholder_widget.dart';
part 'text_form_field_widget.dart';
part 'list_refresh_ndicator.dart';
part 'card_widget.dart';
part 'app_scaffold.dart';
part 'basic_dropdown.dart';
part 'status_bar_widget.dart';
part 'app_divider.dart';
part 'outline_text_button.dart';
part 'outline_button.dart';
part 'text_widget.dart';
part 'header_widget.dart';
part 'app_bottom_sheet.dart';
part 'heightbox.dart';
part 'logo_primary.dart';
part 'widthbox.dart';
part 'app_alert_dialog.dart';
part 'text_form_field_with_label.dart';
part 'progress_bar_scaffold.dart';
part 'border_card_tile.dart';
part 'car_details_widget.dart';
part 'appbar_leading_icon.dart';
part 'country_code_dropdown.dart';
part 'profile_photo_widget.dart';
part 'circle_image_widget.dart';
part 'empty_content_widget.dart';
